dist: bionic
sudo: required

services:
  - docker

language: python
python:
  - "3.6"

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - DOCKER_VERSION=18.06.0~ce-0~ubuntu
    - OPENSHIFT_VERSION=3.9.0
    - OPENSHIFT_COMMIT=191fece
  matrix:
    - TO_TEST=pman
    - TO_TEST=cube

before_install:
  - sudo apt-get install libcurl4-openssl-dev libssl-dev
  - if [ "$TO_TEST" = "cube" ]; then ./cube_before_install.sh; fi

# command to install dependencies
install:
  - if [ "$TO_TEST" = "pman" ]; then pip install .; fi

before_script:
  - if [ "$TO_TEST" = "cube" ]; then ./cube_before_script.sh; fi

# command to run tests
script:
  - if [ "$TO_TEST" = "pman" ]; then nosetests; fi
  - if [ "$TO_TEST" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml exec chris_dev python manage.py test --tag integration --exclude-tag error-pman; fi

after_script:
  - if [ "$TO_TEST" = "cube" ]; then cd ../ChRIS_ultron_backEnd/; docker-compose -f docker-compose_dev.yml down -v; sudo rm -fr ./FS; docker swarm leave --force; fi

notifications:
  slack: fnndsc:xcwPXeUGBBNRkwAlygS9gtCo